services:
  - type: web
    name: quizz-up
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: ADMIN_PASSWORD
        sync: false
